const SUPABASE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxYnlyZXRhdHdwZ21xbG1jcnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDkzNzYyMDcsImV4cCI6MTk2NDk1MjIwN30.gmgAiYEhamVFjYkuTwmyeyAe66IpzUcL4soDgrmItNg";

const SUPABASE_SERVICE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxYnlyZXRhdHdwZ21xbG1jcnBpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY0OTM3NTIxNSwiZXhwIjoxOTY0OTUxMjE1fQ.zSE7QonrYxm9ewZ-yIM4-24pcAhQxDrTKE96dIk2cyQ";

const SUPABASE_URL = "https://rqbyretatwpgmqlmcrpi.supabase.co";

module.exports = { SUPABASE_KEY, SUPABASE_SERVICE_KEY, SUPABASE_URL };
